name: test

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
          }
    steps:
      - uses: actions/checkout@v3
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: Build
        working-directory: ./build
        run: cmake --build . -j --config ${{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j -C ${{ matrix.config.config }}
